export const INIT_USER_INFO = 'INIT_USER_INFO'
export const UPDATE_LANG = 'UPDATE_LANG'
export const INIT_CONTACTS = 'INIT_CONTACTS'
export const INIT_TIMETIME = 'INIT_TIMETIME'
export const UPDATE_TIMETIME = 'UPDATE_TIMETIME'
// self made
export const GET_HOT = 'GET_HOT'
export const GET_NEW = 'GET_NEW'
export const GET_ARITCLE_DETAIL = 'GET_ARITCLE_DETAIL'
export const GET_COMMENT = 'GET_COMMENT'
